# file: kube/demo/3-kafka-topic.yaml
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: my-topic
  namespace: demo
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 100
  replicas: 1
