apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: docker.io/burrsutter/kafka-producer:1.0.0
        imagePullPolicy: Always # because I am in development-mode
        env:
        - name: MP_MESSAGING_OUTGOING_MYSTREAM_BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap.kafka-service:9092
        ports:
          - containerPort: 8080
        resources:
          requests: 
            memory: "60Mi" 
            cpu: "250m" 
          limits:
            memory: "100Mi"
            cpu: "250m" 
